version: '3.8'

services:
  po-hurst-monitor:
    image: monitor
    build: ./paper-engine-monitor
    container_name: po-hurst-monitor
    env_file: ./env/monitor.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  am-monitor:
    image: monitor
    container_name: am-monitor
    env_file: ./env/am-monitor.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  po-hurst-orders:
    build: ./paper-engine-orders
    container_name: po-hurst-orders
    env_file: ./env/orders.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  po-hurst-strategy:
    build: ./paper-engine-strategy
    container_name: po-hurst-strategy
    env_file: ./env/strategy.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sma-monitor:
    image: monitor
    container_name: sma-monitor
    env_file: ./env/sma-monitor.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sma-orders:
    build: ./paper-engine-orders
    container_name: sma-orders
    env_file: ./env/sma-orders.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sma-strategy:
    build: ./paper-engine-strategy
    container_name: sma-strategy
    env_file: ./env/sma-strategy.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"